### ISSUE TITLE
Unknown type name 'zend_rsrc_list_entry'

### ISSUE THREAD

**Issue by rjma30** [LawnGnome/php-radius#3]
Hi, Can't compile on FreeBSD 11.2 using PHP 7.2. I'm getting error below:

checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
[root@AZREUTRI01 /tmp/php-radius]# make
/bin/sh /tmp/php-radius/libtool --mode=compile cc  -I. -I/tmp/php-radius -DPHP_ATOM_INC -I/tmp/php-radius/include -I/tmp/php-radius/main -I/tmp/php-radius -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/php-radius/radius.c -o radius.lo
mkdir .libs
 cc -I. -I/tmp/php-radius -DPHP_ATOM_INC -I/tmp/php-radius/include -I/tmp/php-radius/main -I/tmp/php-radius -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/php-radius/radius.c  -fPIC -DPIC -o .libs/radius.o
/tmp/php-radius/radius.c:52:20: error: unknown type name 'zend_rsrc_list_entry'
void _radius_close(zend_rsrc_list_entry *rsrc TSRMLS_DC);
                   ^
/tmp/php-radius/radius.c:164:3: warning: implicit declaration of function 'ZEND_REGISTER_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
                ZEND_REGISTER_RESOURCE(return_value, raddesc, le_radius);
                ^
/tmp/php-radius/radius.c:181:3: warning: implicit declaration of function 'ZEND_REGISTER_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
                ZEND_REGISTER_RESOURCE(return_value, raddesc, le_radius);
                ^
/tmp/php-radius/radius.c:199:2: warning: implicit declaration of function 'ZEND_FETCH_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
        ^
/tmp/php-radius/radius.c:199:31: error: unexpected type name 'radius_descriptor': expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                     ^
/tmp/php-radius/radius.c:199:50: error: expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                                        ^
/tmp/php-radius/radius.c:200:19: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'zend_resource *'
      (aka 'struct _zend_resource *') [-Wint-conversion]
        zend_list_delete(raddesc->id);
                         ^~~~~~~~~~~
/usr/local/include/php/Zend/zend_list.h:59:46: note: passing argument to parameter 'res' here
ZEND_API int zend_list_delete(zend_resource *res);
                                             ^
/tmp/php-radius/radius.c:216:2: warning: implicit declaration of function 'ZEND_FETCH_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
        ^
/tmp/php-radius/radius.c:216:31: error: unexpected type name 'radius_descriptor': expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                     ^
/tmp/php-radius/radius.c:216:50: error: expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                                        ^
/tmp/php-radius/radius.c:218:35: error: too many arguments provided to function-like macro invocation
        RETURN_STRINGL(msg, strlen(msg), 1);
                                         ^
/usr/local/include/php/Zend/zend_API.h:662:9: note: macro 'RETURN_STRINGL' defined here
#define RETURN_STRINGL(s, l)                    { RETVAL_STRINGL(s, l); return; }
        ^
/tmp/php-radius/radius.c:218:2: error: use of undeclared identifier 'RETURN_STRINGL'
        RETURN_STRINGL(msg, strlen(msg), 1);
        ^
/tmp/php-radius/radius.c:234:2: warning: implicit declaration of function 'ZEND_FETCH_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
        ^
/tmp/php-radius/radius.c:234:31: error: unexpected type name 'radius_descriptor': expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                     ^
/tmp/php-radius/radius.c:234:50: error: expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                                        ^
/tmp/php-radius/radius.c:261:2: warning: implicit declaration of function 'ZEND_FETCH_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
        ^
/tmp/php-radius/radius.c:261:31: error: unexpected type name 'radius_descriptor': expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                     ^
/tmp/php-radius/radius.c:261:50: error: expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                                        ^
/tmp/php-radius/radius.c:282:2: warning: implicit declaration of function 'ZEND_FETCH_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
        ^
/tmp/php-radius/radius.c:282:31: error: unexpected type name 'radius_descriptor': expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                     ^
/tmp/php-radius/radius.c:282:50: error: expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                                        ^
/tmp/php-radius/radius.c:307:2: warning: implicit declaration of function 'ZEND_FETCH_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
        ^
/tmp/php-radius/radius.c:307:31: error: unexpected type name 'radius_descriptor': expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                     ^
/tmp/php-radius/radius.c:307:50: error: expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                                        ^
/tmp/php-radius/radius.c:332:2: warning: implicit declaration of function 'ZEND_FETCH_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
        ^
/tmp/php-radius/radius.c:332:31: error: unexpected type name 'radius_descriptor': expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                     ^
/tmp/php-radius/radius.c:332:50: error: expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                                        ^
/tmp/php-radius/radius.c:359:2: warning: implicit declaration of function 'ZEND_FETCH_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
        ^
/tmp/php-radius/radius.c:359:31: error: unexpected type name 'radius_descriptor': expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                     ^
/tmp/php-radius/radius.c:359:50: error: expected expression
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
                                                        ^
/tmp/php-radius/radius.c:388:2: warning: implicit declaration of function 'ZEND_FETCH_RESOURCE' is invalid in C99 [-Wimplicit-function-declaration]
        ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
12 warnings and 20 errors generated.
*** Error code 1

Stop.
make: stopped in /tmp/php-radius

**Comment by Vinkyweb** [comment]
Hello, I am getting same issue. were you able to sort it? I am using PHP 7.4 with Fileinfo-1.0.4. Thanks.
